### PR TITLE
Updating golang version in dockerfile

### PR DESCRIPTION
**Pull request by PeterEFinch**
Updating golang version in docker file to 1.23.

### CODE REVIEW

**Review by tony-assembly — DISMISSED** [review]
awkward that the data team need to review this 😓 we might need to update that somehow

**Comment by PeterEFinch** [comment]
> awkward that the data team need to review this 😓 we might need to update that somehow

I have asked for help in github-help: https://mx51.slack.com/archives/C07U1P15XRC/p1731383522039509

**Review by aquam8 — DISMISSED** [review]
👍

**Comment by PeterEFinch** [comment]
Discussion on pipeline failure: https://mx51.slack.com/archives/CUH1AEUBD/p1731383384334679

**Review by aquam8 — APPROVED** [review]
Thank you Adam!

**Comment by aquam8** [comment]
I have approved and merged as Admin since there is no Data user that can approve

**Pull request merged**
